// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TGHarker.Insights.Abstractions.Models.Generated;

#nullable disable

namespace TGHarker.Insights.Silo.Migrations
{
    [DbContext(typeof(SearchDesignTimeContext))]
    [Migration("20260202165229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.ApplicationStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("SearchVector")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("Domain")
                        .HasDatabaseName("IX_ApplicationState_Domain");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ApplicationState_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_ApplicationState_Name");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_ApplicationState_OrganizationId");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_ApplicationState_OwnerId");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_ApplicationState_SearchVector");

                    b.ToTable("ApplicationStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.ConversionStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("GoalId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UtmCampaign")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("VisitorId")
                        .HasColumnType("text");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_ConversionState_ApplicationId");

                    b.HasIndex("GoalId")
                        .HasDatabaseName("IX_ConversionState_GoalId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_ConversionState_SessionId");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_ConversionState_Source");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_ConversionState_Timestamp");

                    b.HasIndex("UtmCampaign")
                        .HasDatabaseName("IX_ConversionState_UtmCampaign");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("IX_ConversionState_VisitorId");

                    b.ToTable("ConversionStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.DailyMetricsStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<int>("Bounces")
                        .HasColumnType("integer");

                    b.Property<decimal>("ConversionValue")
                        .HasColumnType("numeric");

                    b.Property<int>("Conversions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Events")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageViews")
                        .HasColumnType("integer");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueVisitors")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_DailyMetricsState_ApplicationId");

                    b.HasIndex("Bounces")
                        .HasDatabaseName("IX_DailyMetricsState_Bounces");

                    b.HasIndex("ConversionValue")
                        .HasDatabaseName("IX_DailyMetricsState_ConversionValue");

                    b.HasIndex("Conversions")
                        .HasDatabaseName("IX_DailyMetricsState_Conversions");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_DailyMetricsState_Date");

                    b.HasIndex("Events")
                        .HasDatabaseName("IX_DailyMetricsState_Events");

                    b.HasIndex("PageViews")
                        .HasDatabaseName("IX_DailyMetricsState_PageViews");

                    b.HasIndex("Sessions")
                        .HasDatabaseName("IX_DailyMetricsState_Sessions");

                    b.HasIndex("TotalDurationSeconds")
                        .HasDatabaseName("IX_DailyMetricsState_TotalDurationSeconds");

                    b.HasIndex("UniqueVisitors")
                        .HasDatabaseName("IX_DailyMetricsState_UniqueVisitors");

                    b.ToTable("DailyMetricsStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.EventStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SearchVector")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("VisitorId")
                        .HasColumnType("text");

                    b.HasKey("GrainId");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_EventState_Action");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_EventState_ApplicationId");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_EventState_Category");

                    b.HasIndex("Label")
                        .HasDatabaseName("IX_EventState_Label");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_EventState_SearchVector");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_EventState_SessionId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_EventState_Timestamp");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("IX_EventState_VisitorId");

                    b.ToTable("EventStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.FunnelStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SearchVector")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_FunnelState_ApplicationId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FunnelState_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_FunnelState_Name");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_FunnelState_SearchVector");

                    b.ToTable("FunnelStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.GoalStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SearchVector")
                        .HasColumnType("text");

                    b.Property<int>("TotalConversions")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_GoalState_ApplicationId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_GoalState_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_GoalState_Name");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_GoalState_SearchVector");

                    b.HasIndex("TotalConversions")
                        .HasDatabaseName("IX_GoalState_TotalConversions");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_GoalState_Type");

                    b.ToTable("GoalStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.HourlyMetricsStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<int>("Bounces")
                        .HasColumnType("integer");

                    b.Property<decimal>("ConversionValue")
                        .HasColumnType("numeric");

                    b.Property<int>("Conversions")
                        .HasColumnType("integer");

                    b.Property<int>("Events")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HourStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageViews")
                        .HasColumnType("integer");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueVisitors")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_HourlyMetricsState_ApplicationId");

                    b.HasIndex("Bounces")
                        .HasDatabaseName("IX_HourlyMetricsState_Bounces");

                    b.HasIndex("ConversionValue")
                        .HasDatabaseName("IX_HourlyMetricsState_ConversionValue");

                    b.HasIndex("Conversions")
                        .HasDatabaseName("IX_HourlyMetricsState_Conversions");

                    b.HasIndex("Events")
                        .HasDatabaseName("IX_HourlyMetricsState_Events");

                    b.HasIndex("HourStart")
                        .HasDatabaseName("IX_HourlyMetricsState_HourStart");

                    b.HasIndex("PageViews")
                        .HasDatabaseName("IX_HourlyMetricsState_PageViews");

                    b.HasIndex("Sessions")
                        .HasDatabaseName("IX_HourlyMetricsState_Sessions");

                    b.HasIndex("TotalDurationSeconds")
                        .HasDatabaseName("IX_HourlyMetricsState_TotalDurationSeconds");

                    b.HasIndex("UniqueVisitors")
                        .HasDatabaseName("IX_HourlyMetricsState_UniqueVisitors");

                    b.ToTable("HourlyMetricsStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.PageViewStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PagePath")
                        .HasColumnType("text");

                    b.Property<string>("PageTitle")
                        .HasColumnType("text");

                    b.Property<int>("ScrollDepthPercent")
                        .HasColumnType("integer");

                    b.Property<string>("SearchVector")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<int>("TimeOnPageSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("VisitorId")
                        .HasColumnType("text");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_PageViewState_ApplicationId");

                    b.HasIndex("PagePath")
                        .HasDatabaseName("IX_PageViewState_PagePath");

                    b.HasIndex("PageTitle")
                        .HasDatabaseName("IX_PageViewState_PageTitle");

                    b.HasIndex("ScrollDepthPercent")
                        .HasDatabaseName("IX_PageViewState_ScrollDepthPercent");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_PageViewState_SearchVector");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_PageViewState_SessionId");

                    b.HasIndex("TimeOnPageSeconds")
                        .HasDatabaseName("IX_PageViewState_TimeOnPageSeconds");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_PageViewState_Timestamp");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("IX_PageViewState_VisitorId");

                    b.ToTable("PageViewStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.RetentionCohortStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("CohortWeek")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalVisitors")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_RetentionCohortState_ApplicationId");

                    b.HasIndex("CohortWeek")
                        .HasDatabaseName("IX_RetentionCohortState_CohortWeek");

                    b.HasIndex("TotalVisitors")
                        .HasDatabaseName("IX_RetentionCohortState_TotalVisitors");

                    b.ToTable("RetentionCohortStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.SessionStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExitPage")
                        .HasColumnType("text");

                    b.Property<bool>("HasConversion")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBounce")
                        .HasColumnType("boolean");

                    b.Property<string>("LandingPage")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PageViewCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReferrerDomain")
                        .HasColumnType("text");

                    b.Property<string>("ReferrerUrl")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UtmCampaign")
                        .HasColumnType("text");

                    b.Property<string>("UtmMedium")
                        .HasColumnType("text");

                    b.Property<string>("UtmSource")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("VisitorId")
                        .HasColumnType("text");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_SessionState_ApplicationId");

                    b.HasIndex("DurationSeconds")
                        .HasDatabaseName("IX_SessionState_DurationSeconds");

                    b.HasIndex("EventCount")
                        .HasDatabaseName("IX_SessionState_EventCount");

                    b.HasIndex("ExitPage")
                        .HasDatabaseName("IX_SessionState_ExitPage");

                    b.HasIndex("HasConversion")
                        .HasDatabaseName("IX_SessionState_HasConversion");

                    b.HasIndex("IsBounce")
                        .HasDatabaseName("IX_SessionState_IsBounce");

                    b.HasIndex("LandingPage")
                        .HasDatabaseName("IX_SessionState_LandingPage");

                    b.HasIndex("PageViewCount")
                        .HasDatabaseName("IX_SessionState_PageViewCount");

                    b.HasIndex("ReferrerDomain")
                        .HasDatabaseName("IX_SessionState_ReferrerDomain");

                    b.HasIndex("ReferrerUrl")
                        .HasDatabaseName("IX_SessionState_ReferrerUrl");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_SessionState_Source");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_SessionState_StartedAt");

                    b.HasIndex("UtmCampaign")
                        .HasDatabaseName("IX_SessionState_UtmCampaign");

                    b.HasIndex("UtmMedium")
                        .HasDatabaseName("IX_SessionState_UtmMedium");

                    b.HasIndex("UtmSource")
                        .HasDatabaseName("IX_SessionState_UtmSource");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("IX_SessionState_VisitorId");

                    b.ToTable("SessionStates", (string)null);
                });

            modelBuilder.Entity("TGHarker.Insights.Abstractions.Models.Generated.VisitorStateEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPageViews")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("GrainId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_VisitorState_ApplicationId");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_VisitorState_City");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_VisitorState_Country");

                    b.HasIndex("FirstSeen")
                        .HasDatabaseName("IX_VisitorState_FirstSeen");

                    b.HasIndex("LastSeen")
                        .HasDatabaseName("IX_VisitorState_LastSeen");

                    b.HasIndex("TotalPageViews")
                        .HasDatabaseName("IX_VisitorState_TotalPageViews");

                    b.HasIndex("TotalSessions")
                        .HasDatabaseName("IX_VisitorState_TotalSessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_VisitorState_UserId");

                    b.ToTable("VisitorStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
